### ISSUE TITLE
training strategy

### ISSUE THREAD

**Issue by wgh-2018** [lly00412/SEDNet#2]
Hi！in the scripts,different datasets are used. Can i mix different datasets during training? will it get something wrong in loss.

**Comment by lly00412** [comment]
The loss is defined as a per-pixel loss. If you want to mix different datasets, you need to ensure the inputs of stereo pairs should be the same size and have the same disparity range for the cost volume.

**Comment by wgh-2018** [comment]
Thanks a lot for the reply!
