### ISSUE TITLE
some question about soft_assignment

### ISSUE THREAD

**Issue by CC9310** [lly00412/SEDNet#5]
Uncertainty and disp_loss are two different modal, but I notice the UCLoss use disp_loss 

y_dist = 10 * torch.exp(-(x_hat - y)**2 / 5)

to build the distribution, how to explain this formulation? 

e.g. disp_loss = 1.0, that the estimate uncertainty=0, because e**0 = 1?

**Comment by Terry10086** [comment]
I also have the same confusion. Why are the hyper-parameters λ1 equal to 10 and λ2 equal to 5?

**Comment by lly00412** [comment]
> Uncertainty and disp_loss are two different modal, but I notice the UCLoss use disp_loss
> 
> y_dist = 10 * torch.exp(-(x_hat - y)**2 / 5)
> 
> to build the distribution, how to explain this formulation?
> 
> e.g. disp_loss = 1.0, that the estimate uncertainty=0, because e**0 = 1?

Please read our paper Section 3.2.

**Comment by lly00412** [comment]
> I also have the same confusion. Why are the hyper-parameters λ1 equal to 10 and λ2 equal to 5?

The two hyper-params are used to control the shape of the Laplace distribution not to be too thin or too smooth. You can also try some other numbers, but the results should not be too much different.

**Comment by Terry10086** [comment]
> > I also have the same confusion. Why are the hyper-parameters λ1 equal to 10 and λ2 equal to 5?
> 
> The two hyper-params are used to control the shape of the Laplace distribution not to be too thin or too smooth. You can also try some other numbers, but the results should not be too much different.

Thank you so much!
